### ISSUE TITLE
Add Sequelize

### ISSUE THREAD

**Issue by cameronRomo** [cameronRomo/node-basics#1]
### Notes: 
  * Sequelize is an Object-Relational Mapping library (ORM) that can help to map a regular javascript object to its relevant SQL queries.

### Tasks:
- [x] Connect to db
- [x] Add Product model
- [x] Adds functionality to create a product
- [x] Retrieve data
- [x] Fetch admin products
  - [x] Update a product
  - [x] Delete a product
- [x] Add User model
  - [x] Add one-to-many relationship
- [x] Add Cart model
  - [x] Add to cart
  - [x] Delete from cart
- [x] Add Order model
  - [x] Store CartItems as OrderItems
  - [x] Add functionality to reset cart

**Comment by cameronRomo** [comment]
Sequelize's `findById()` has changed to `findByPk()`

**Comment by cameronRomo** [comment]
[Sequelize Official Docs](http://docs.sequelizejs.com/)

**Comment by cameronRomo** [comment]
Relationships:
```
product <------- Has Many ------------- User
    |                                     |
    |- Blgs to Many -> Cart <- Has One----|
    |- Blgs to Many -> Order <- Has Many--|
```
