### ISSUE TITLE
Change from SQL to noSQL

### ISSUE THREAD

**Issue by cameronRomo** [cameronRomo/node-basics#3]
### Notes: 
  * MongoDB is schemaless
    * Fewer data relationships
    * Can be visualized as db (Shop) -> Collections (Users & Orders) -> Documents (data entry point).
      *  Documents are stored as JSON (BSON - Binary JSON).
    * Relationships are different.
      *  Two typical patterns exist
        * Nest the data
        * Use references to other documents/collections
  
### Tasks:
- [ ] Settup MongoDB
  - [ ] Install Driver
  - [ ] Connect to DB
- [ ] Add Products functionality
  - [ ] Get all
  - [ ] Get a specific product
  - [ ] Update
  - [ ] Delete
  - [ ] Post
- [ ] Add Users
  - [ ] Store User
  - [ ] Functionality for a user to have a cart and orders
  - [ ] Store multiple products in Cart
  - [ ] Display cart items
  - [ ] Delete cart items
  - [ ] get orders
